# coding: utf-8

"""
    qc_qubosolv

    Client SDK for main incubator Quantum Annealer.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "qc_qubosolv"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools    

with open('requirements.txt') as f:
    requirements = [s.strip() for s in f.readlines()]


setup(
    name=NAME,
    version=VERSION,
    description="qc_qubosolv",
    author_email="",
    url="",
    keywords=["qc_qubosolv"],
    install_requires=requirements,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Client SDK for main incubator Quantum Annealer.  # noqa: E501
    """
)
