# coding: utf-8

"""
    qc_qubosolv_api

    main incubator Quantum Annealer (qc_qubosolv).  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Task(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'matrix': 'list[list[int]]',
        'parameter': 'Parameter'
    }

    attribute_map = {
        'matrix': 'matrix',
        'parameter': 'parameter'
    }

    def __init__(self, matrix=None, parameter=None):  # noqa: E501
        """Task - a model defined in Swagger"""  # noqa: E501

        self._matrix = None
        self._parameter = None
        self.discriminator = None

        if matrix is not None:
            self.matrix = matrix
        if parameter is not None:
            self.parameter = parameter

    @property
    def matrix(self):
        """Gets the matrix of this Task.  # noqa: E501


        :return: The matrix of this Task.  # noqa: E501
        :rtype: list[list[int]]
        """
        return self._matrix

    @matrix.setter
    def matrix(self, matrix):
        """Sets the matrix of this Task.


        :param matrix: The matrix of this Task.  # noqa: E501
        :type: list[list[int]]
        """

        self._matrix = matrix

    @property
    def parameter(self):
        """Gets the parameter of this Task.  # noqa: E501


        :return: The parameter of this Task.  # noqa: E501
        :rtype: Parameter
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this Task.


        :param parameter: The parameter of this Task.  # noqa: E501
        :type: Parameter
        """

        self._parameter = parameter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Task, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Task):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
